artifact_location: file:///C:/Users/Admin/Documents/1.All%20Projects%20in%20guvi/SmartPremium%20Insurance%20Prediction/mlruns/330623987575488957
creation_time: 1741935329310
experiment_id: '330623987575488957'
last_update_time: 1741935329310
lifecycle_stage: active
name: SmartPremium_InsurancePrediction
